name: Build and Test

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
  pull_request:

jobs:
  prerelease:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          package-manager-cache: false
      - name: Prepare Environment
        run: yarn install --frozen-lockfile
        env:
          CI: true
      - name: Build
        run: yarn build
        env:
          CI: true
