name: Publish to NPM

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prerelease:
    name: Publish to NPM
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Use Node.js 22
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Prepare Environment
        run: |
          yarn install
        env:
          CI: true
      - name: Build
        run: |
          yarn build
        env:
          CI: true
      - name: Publish to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          NEW_VERSION=$(node -p "require('./package.json').version")
          yarn publish --access=public --new-version=$NEW_VERSION --network-timeout 100000
        env:
          CI: true
